import { Inter } from "next/font/google";
import "./globals.css";
import App from "./App";
import AuthProvider from "@/providers/AuthProvider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg" href="/home.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {/* <App /> */}
          {/* {children} */}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
